### ISSUE TITLE
important rule

### ISSUE THREAD

**Issue by StudioSpindle** [dorel/polymer-spa-dorel-juvenile#324]
https://github.com/dorel/polymer-spa-dorel-juvenile/blob/ddfa1738ad5038124ef796063cf0d6959f99cec1/src/atoms/dorel-cta.html#L10

@petercuret  Is this !important statement necessary? 

If so, can you add a comment?

**Comment by petercuret** [comment]
It was necessary in some case, but this been solved in a cleaner way now.
