### ISSUE TITLE
Is this brand agnostic? 

### ISSUE THREAD

**Issue by StudioSpindle** [dorel/polymer-spa-dorel-juvenile#327]
Is this line brand agnostic? 
What is the purpose of this comment? 

https://github.com/dorel/polymer-spa-dorel-juvenile/blob/046c0a8e916dd229ccf3e3cc54e883e069dc1df5/src/themes/theme-dorel-shared-styles.html#L16

**Comment by petercuret** [comment]
This can be removed, it's deprecated.

**Comment by petercuret** [comment]
Cleaned up in DIO-1739
