### ISSUE TITLE
gutter variable, correct defined?

### ISSUE THREAD

**Issue by StudioSpindle** [dorel/polymer-spa-dorel-juvenile#334]
Shouldn't it have a `--` in front?

https://github.com/dorel/polymer-spa-dorel-juvenile/blob/3e759772e9bd3f5e69b46da3be9f082e989c626c/src/themes/theme-dorel-shared-styles.html#L69

(this also applies for maxi-cosi and quinny shared styles)

**Comment by petercuret** [comment]
@StudioSpindle Looks like a bug!

**Comment by petercuret** [comment]
Resolved
